#cloud-config

yum_repos:
  docker:
    baseurl: https://download.docker.com/linux/centos/docker-ce.repo
    enabled: true
    gpgcheck: false
    name: Docker repo

packages:
  docker-ce
  docker-ce-cli
  containerd.io
  docker-buildx-plugin
  docker-compose-plugin

package_upgrade: true

# create the docker group
groups:
  - docker

# Add default auto created user to docker group
system_info:
  default_user:
    groups: [docker]

runcmd:
  - [systemctl start docker]
